### ISSUE TITLE
Is it nessary to add head and tail to every single sql?

### ISSUE THREAD

**Issue by seua** [afrase/mysqldumpsplit#1]
Is it nessary to add head and tail to every single sql? 
I mean the /*!40101 SET @OLD_CHARACTER_SET_xxxxxxxxxxxxxxxxxxxx  and so on.

And by the way  I built the project and have some try. I think it is very useful.

**Comment by afrase** [comment]
Probably not but for what I used it for I need to have it or I would get an error about timestamps being incorrect. I could probably pull it out of the input file and add it back instead of hardcoding the values.

**Comment by afrase** [comment]
Newest release doesn't hard code the header info.
