### ISSUE TITLE
Thanks a lot ! 

### ISSUE THREAD

**Issue by or2me** [afrase/mysqldumpsplit#2]
this project helps me a lot ! may you add those futures ?
1, dump per table as .CSV 
some individual table files are still tool huge for importing to mysql use "source" command, i have to turn the .SQL files to .CSV so i will be able to use "load file";
2,use wildcard characters for skipData  parameter
so i can skip all the tables which contains word like "_bak_" in name.

thank you very much ! Agin!

**Comment by afrase** [comment]
Thanks, I'm glad you found the tool useful.

The wildcard for skipping tables should be a simple feature. I'll see if I can add that soon.

Being able to convert table data to CSV might be a bit out of scope for this tool. I would probably have to create a SQL parser to correctly be able to output the data. This could also cause the application to have to keep an entire tables content in RAM. That would break one of the original goals of the project. I'll take a closer look at it when I have time.

Thanks,
Aaron

**Comment by afrase** [comment]
Version v0.1.0 has support for wildcards.
